### ISSUE TITLE
'Nvim' object has no attribute 'run_loop'

### ISSUE THREAD

**Issue by tomleo** [neovim/python-gui#20]
```
tom@desktop:~$ pynvim&
[1] 7140
tom@desktop:~$ Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/neovim_gui/ui_bridge.py", line 104, in _nvim_event_loop
    self._nvim.run_loop(on_request, on_notification, on_setup)
AttributeError: 'Nvim' object has no attribute 'run_loop'
```

**Comment by bfredl** [comment]
you need to update python-client to 0.1.7:

```
pip2 install --upgrade neovim
```

**Comment by tomleo** [comment]
@bfredl thanks
