### ISSUE TITLE
Installation of module using Python 3 fails on `pygobject` dependency

### ISSUE THREAD

**Issue by unclechu** [neovim/python-gui#30]
``` bash
$ pip3 install neovim-gui
Collecting neovim-gui
  Using cached neovim_gui-0.1.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): neovim>=0.1.3 in ./.venv/lib/python3.4/site-packages (from neovim-gui)
Collecting click>=3.0 (from neovim-gui)
  Using cached click-6.6.tar.gz
Collecting pygobject (from neovim-gui)
  Using cached pygobject-2.28.3.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rysp8tff/pygobject/setup.py", line 272
        raise SystemExit, 'ERROR: Nothing to do, gio could not be found and is essential.'
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rysp8tff/pygobject/
```

``` bash
$ python3 -V
Python 3.4.3
```

``` bash
$ pip3 -V
pip 8.1.2 from /home/unclechu/nvim-attach/.venv/lib64/python3.4/site-packages (python 3.4)
```

``` bash
$ uname -a
Linux unclefarm23 4.7.5-100.fc23.x86_64 #1 SMP Mon Sep 26 19:29:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

``` bash
$ cat /etc/fedora-release
Fedora release 23 (Twenty Three)
```

**Comment by justinmk** [comment]
> raise SystemExit, 'ERROR: Nothing to do, gio could not be found and is essential.'
>                       ^
>    SyntaxError: invalid syntax

That is not valid syntax in python 3. Did you get a cached python 2 egg in your python 3 path, somehow?

This is a third party issue, not much we can do here.
