### ISSUE TITLE
ValueError: Namespace Gtk not available

### ISSUE THREAD

**Issue by trusktr** [neovim/python-gui#33]
running `pynvim` says:

```
~ ❯ pynvim
Traceback (most recent call last):
  File "/usr/local/bin/pynvim", line 9, in <module>
    load_entry_point('neovim-gui==0.1.3', 'console_scripts', 'pynvim')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/neovim_gui/cli.py", line 63, in main
    from .gtk_ui import GtkUI
  File "/usr/local/lib/python2.7/site-packages/neovim_gui/gtk_ui.py", line 8, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/local/lib/python2.7/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

**Comment by justinmk** [comment]
Seems like a missing dependency.

https://github.com/neovim/python-gui#dependencies-debian
