### ISSUE TITLE
python-gui raises exception on launch

### ISSUE THREAD

**Issue by dnyaneshgate** [neovim/python-gui#34]
I am using Ubuntu-16.04 Gnome3.
Python-GUI installed using 'pip install neovim-gui'

Getting following exception on running command pynvim

> root@dnyaneshg-Lenovo-ideapad-Y700-15ISK:~/Projects/stunpp# pynvim 
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/neovim_gui/gtk_ui.py", line 138, in wrapper
>     self._flush()
>   File "/usr/local/lib/python2.7/dist-packages/neovim_gui/gtk_ui.py", line 457, in _flush
>     self._pending[0] = self._screen.row
> AttributeError: 'NoneType' object has no attribute 'row'
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/neovim_gui/gtk_ui.py", line 138, in wrapper
>     self._flush()
>   File "/usr/local/lib/python2.7/dist-packages/neovim_gui/gtk_ui.py", line 457, in _flush
>     self._pending[0] = self._screen.row
> AttributeError: 'NoneType' object has no attribute 'row'
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/neovim_gui/gtk_ui.py", line 138, in wrapper
>     self._flush()
>   File "/usr/local/lib/python2.7/dist-packages/neovim_gui/gtk_ui.py", line 457, in _flush
>     self._pending[0] = self._screen.row
> AttributeError: 'NoneType' object has no attribute 'row'
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/neovim_gui/ui_bridge.py", line 97, in apply_updates
>     handler(*args)
>   File "/usr/local/lib/python2.7/dist-packages/neovim_gui/gtk_ui.py", line 184, in _nvim_cursor_goto
>     self._screen.cursor_goto(row, col)
> AttributeError: 'NoneType' object has no attribute 'cursor_goto'

**Comment by viktorstrate** [comment]
I am using Ubuntu Gnome 17.04. When I try to run `pynvim` from the terminal, a window appears for a seccond. And this is the output from the terminal.
```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/neovim_gui/ui_bridge.py", line 97, in apply_updates
    handler(*args)
TypeError: _nvim_mode_change() takes 2 positional arguments but 3 were given
```

I have installed python-gui using `sudo pip install neovim-gui`

**Comment by bfredl** [comment]
This repo is not really active developed. Maybe https://github.com/rliang/nvim-pygtk3 works better?
